# Generated by Django 4.2.23 on 2026-02-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_rename_and_create_leave_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='payment',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'LOP')], default='unpaid', max_length=30, verbose_name='Is Paid'),
        ),
    ]
