# Generated by Django 4.2.23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0001_add_interview_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewschedule",
            name="interview_link",
            field=models.URLField(
                blank=True,
                help_text="e.g. Google Meet, Zoom or other meeting URL",
                verbose_name="Meeting Link",
            ),
        ),
    ]
