# Generated by Django 4.2.23 on 2026-01-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_add_interview_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='historicalcandidate',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
    ]
