# Generated by Django 4.2.23 on 2026-05-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_rejected_candidate_description_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrejectedcandidate',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='Rejection Email Sent'),
        ),
        migrations.AddField(
            model_name='rejectedcandidate',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='Rejection Email Sent'),
        ),
    ]
