# Generated by Django 4.2.23 on 2026-02-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpringVerificationAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=1)),
            ],
            options={
                'verbose_name': 'Spring Verification Access',
                'verbose_name_plural': 'Spring Verification Access',
            },
        ),
    ]
