# Generated by Django 4.2.23 on 2026-02-03 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_historicalemployeeworkinformation_probation_action'),
        ('spring_verification', '0001_add_springverificationaccess'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='springverificationaccess',
            options={'verbose_name': 'BGV Access', 'verbose_name_plural': 'BGV Access'},
        ),
        migrations.CreateModel(
            name='BGVCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('overall_status', models.CharField(blank=True, max_length=100)),
                ('candidate_id', models.IntegerField(unique=True)),
                ('candidate_uuid', models.CharField(blank=True, max_length=64)),
                ('initiation_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('report_url', models.URLField(blank=True, max_length=500)),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bgv_candidates', to='employee.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'BGV Candidate',
                'verbose_name_plural': 'BGV Candidates',
                'ordering': ['-initiation_date'],
            },
        ),
    ]
