# Generated by Django 4.2.23 on 2026-01-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_user_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('presence', models.CharField(choices=[('active', 'Active'), ('away', 'Away')], default='away', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slack Presence',
                'verbose_name_plural': 'Slack Presences',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='slack_user_id',
            field=models.CharField(blank=True, db_index=True, help_text='Slack user ID (e.g. U01234ABCD) for presence in Online Employees.', max_length=50, null=True, unique=True, verbose_name='Slack User ID'),
        ),
    ]
