# Generated by Django 4.2 on 2026-02-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0003_employeeworkinformation_probation_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalemployeeworkinformation",
            name="probation_action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extended", "Extended"),
                    ("confirmed", "Confirmed"),
                    ("rejected", "Rejected"),
                ],
                max_length=20,
                null=True,
                verbose_name="Probation Action",
            ),
        ),
        migrations.AddField(
            model_name="historicalemployeeworkinformation",
            name="probation_action_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Probation Action Date"
            ),
        ),
    ]
