# Generated by Django 4.2.23 on 2026-03-24 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employee_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkinformation',
            name='business_manager_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_manager', to='employee.employee', verbose_name='Business Manager'),
        ),
        migrations.AddField(
            model_name='employeeworkinformation',
            name='operation_manager_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_manager', to='employee.employee', verbose_name='Operation Manager'),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='business_manager_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employee.employee', verbose_name='Business Manager'),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='operation_manager_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employee.employee', verbose_name='Operation Manager'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Emergency contact number'),
        ),
    ]
