# Generated by Django 4.2.23 on 2026-04-09 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_emaillog_body_textfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0007_employeeworkinformation_business_manager_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(help_text='Name of the team within the department', max_length=100, verbose_name='Team Name')),
                ('description', models.TextField(blank=True, help_text="Brief description of the team's purpose or function", null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_teams', to='base.department', verbose_name='Department')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to='employee.employee', verbose_name='Team Lead')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['team_name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='team_ids',
            field=models.ManyToManyField(blank=True, related_name='team_members', to='employee.team', verbose_name='Teams'),
        ),
    ]
