# Generated by Django 4.2.23 on 2026-04-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_add_team_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='team_ids',
        ),
        migrations.AddField(
            model_name='employeeworkinformation',
            name='team_ids',
            field=models.ManyToManyField(blank=True, related_name='work_team_members', to='employee.team', verbose_name='Teams'),
        ),
    ]
