# Generated by Django 4.2.23 on 2026-02-02 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import horilla.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0004_historicalemployeeworkinformation_probation_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('asset_name', models.CharField(max_length=255, verbose_name='Asset Name')),
                ('asset_description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('asset_tracking_id', models.CharField(max_length=30, unique=True, verbose_name='Asset Id')),
                ('asset_purchase_date', models.DateField(verbose_name='Purchase Date')),
                ('asset_purchase_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost')),
                ('asset_status', models.CharField(choices=[('In use', 'In Use'), ('Available', 'Available'), ('Not-Available', 'Not-Available')], default='Available', max_length=40, verbose_name='Status')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('notify_before', models.IntegerField(default=1, null=True, verbose_name='Notify Before (days)')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('asset_category_name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('asset_category_description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('company_id', models.ManyToManyField(blank=True, to='base.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Asset Category',
                'verbose_name_plural': 'Asset Categories',
            },
        ),
        migrations.CreateModel(
            name='ReturnImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('image', models.FileField(blank=True, null=True, upload_to=horilla.models.upload_path)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('asset_request_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('asset_request_status', models.CharField(blank=True, choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Requested', max_length=30, null=True)),
                ('asset_category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.assetcategory', verbose_name='Asset Category')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('requested_employee_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_employee', to='employee.employee', verbose_name='Requesting User')),
            ],
            options={
                'verbose_name': 'Asset Request',
                'verbose_name_plural': 'Asset Requests',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AssetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_report', to='asset.asset')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('lot_number', models.CharField(max_length=30, unique=True, verbose_name='Batch Number')),
                ('lot_description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('company_id', models.ManyToManyField(blank=True, to='base.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Asset Batch',
                'verbose_name_plural': 'Asset Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('file', models.FileField(blank=True, null=True, upload_to=horilla.models.upload_path)),
                ('asset_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='asset.assetreport')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Asset Document',
                'verbose_name_plural': 'Asset Documents',
            },
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Return Date')),
                ('return_condition', models.TextField(blank=True, max_length=255, null=True, verbose_name='Return Condition')),
                ('return_status', models.CharField(blank=True, choices=[('Minor damage', 'Minor damage'), ('Major damage', 'Major damage'), ('Healthy', 'Healthy')], max_length=30, null=True, verbose_name='Return Status')),
                ('return_request', models.BooleanField(default=False)),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.asset', verbose_name='Asset')),
                ('assign_images', models.ManyToManyField(blank=True, related_name='assign_images', to='asset.returnimages', verbose_name='Assign Condition Images')),
                ('assigned_by_employee_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_by', to='employee.employee', verbose_name='Assigned By')),
                ('assigned_to_employee_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocated_employee', to='employee.employee', verbose_name='Assigned To')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('return_images', models.ManyToManyField(blank=True, related_name='return_images', to='asset.returnimages')),
            ],
            options={
                'verbose_name': 'Asset Allocation',
                'verbose_name_plural': 'Asset Allocations',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.assetcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_lot_number_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='asset.assetlot', verbose_name='Batch No'),
        ),
        migrations.AddField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='asset',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.employee', verbose_name='Current User'),
        ),
    ]
