# Generated by Django 4.2.23 on 2026-07-03 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_remove_employee_team_ids_and_more'),
        ('asset', '0001_asset_category_description_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetassignment',
            name='is_temporary_allocation',
            field=models.BooleanField(default=False, verbose_name='Temporary Allocation'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='temporary_assignee_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Temporary Assignee Name'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='assigned_to_employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocated_employee', to='employee.employee', verbose_name='Assigned To'),
        ),
    ]
