# Generated by Django 4.2.23 on 2026-02-04 09:04

from django.db import migrations, models


def backfill_final_salary(apps, schema_editor):
    """Set final_salary = calculated_salary - pt_deduction for existing rows."""
    MonthlySalaryData = apps.get_model("payroll", "MonthlySalaryData")
    for row in MonthlySalaryData.objects.all():
        row.final_salary = max(0, row.calculated_salary - row.pt_deduction)
        row.save(update_fields=["final_salary"])


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_create_monthly_salary_data_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalarydata',
            name='final_salary',
            field=models.FloatField(default=0, help_text='Calculated salary minus PT', verbose_name='Final Salary'),
        ),
        migrations.AddField(
            model_name='monthlysalarydata',
            name='pt_deduction',
            field=models.FloatField(default=200, help_text='Fixed deduction, default ₹200', verbose_name='PT (Professional Tax)'),
        ),
        migrations.AlterField(
            model_name='monthlysalarydata',
            name='calculated_salary',
            field=models.FloatField(default=0, help_text='(days_worked / working_days) × monthly_salary, before PT', verbose_name='Calculated Salary'),
        ),
        migrations.RunPython(backfill_final_salary, migrations.RunPython.noop),
    ]
