# Generated by Django 4.2.23 on 2026-03-24 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_monthlysalarydata_archived'),
        ('payroll', '0007_add_id_field'),
    ]

    operations = [
    ]
