# Generated by Django 4.2.23 on 2026-04-07 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0008_merge_20260324_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryDataAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('generated', 'Generated'), ('deleted_single', 'Deleted (single)'), ('deleted_bulk', 'Deleted (bulk)')], max_length=20, verbose_name='Action')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('month', models.IntegerField(blank=True, null=True, verbose_name='Month')),
                ('summary', models.TextField(blank=True, default='', verbose_name='Details')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='Date & time')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_data_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Salary Data activity log',
                'verbose_name_plural': 'Salary Data activity logs',
                'ordering': ['-performed_at'],
            },
        ),
    ]
