# Generated by Django 4.2.23 on 2026-06-08 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import horilla.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0009_remove_employee_team_ids_and_more'),
        ('payroll', '0009_salary_data_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('expense_date', models.DateField(verbose_name='Date')),
                ('description', models.TextField(max_length=500, verbose_name='Description / Purpose')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount')),
                ('mode_of_payment', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('credit_card', 'Credit Card'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=20, verbose_name='Mode of Payment')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Payment Status')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=horilla.models.upload_path, verbose_name='Receipt / Document')),
                ('archived', models.BooleanField(default=False, help_text='Archived expenses are hidden from the default list.', verbose_name='Archived')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses_added', to='employee.employee', verbose_name='Added By')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-expense_date', '-id'],
            },
        ),
    ]
