# Generated by Django 4.2.23 on 2026-06-08 08:51

from decimal import Decimal

from django.db import migrations, models
import django.db.models.deletion


def migrate_amount_to_breakups(apps, schema_editor):
    Expense = apps.get_model("payroll", "Expense")
    ExpenseBreakup = apps.get_model("payroll", "ExpenseBreakup")
    for expense in Expense.objects.all():
        amount = getattr(expense, "amount", None) or Decimal("0")
        if amount:
            ExpenseBreakup.objects.create(
                expense_id=expense.id,
                particular="Total",
                amount=amount,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0010_expense"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseBreakup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "particular",
                    models.CharField(max_length=255, verbose_name="Particular"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breakups",
                        to="payroll.expense",
                        verbose_name="Expense",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense Breakup",
                "verbose_name_plural": "Expense Breakups",
                "ordering": ["id"],
            },
        ),
        migrations.RunPython(migrate_amount_to_breakups, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="expense",
            name="mode_of_payment",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Mode of Payment"
            ),
        ),
        migrations.RemoveField(
            model_name="expense",
            name="amount",
        ),
    ]
