# Generated by Django 4.2.23 on 2026-06-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_expense_breakup_and_mode_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Description / Purpose'),
        ),
    ]
