# Generated by Django 4.2.23 on 2026-06-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_expense_description_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='paid_by',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Paid By'),
        ),
        migrations.AddField(
            model_name='expensebreakup',
            name='category',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Category'),
        ),
    ]
