# Generated by Django 4.2.23 on 2026-05-21 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_emaillog_body_textfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamicemailconfiguration',
            options={},
        ),
        migrations.CreateModel(
            name='SlackConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('slack_bot_token', models.CharField(blank=True, help_text='Bot User OAuth Token with users:read scope', max_length=256, null=True, verbose_name='Slack Bot Token')),
                ('is_active', models.BooleanField(default=True, verbose_name='Enable Slack Integration')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
