# Generated by Django 4.2.23 on 2026-05-21 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_dynamicemailconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slackconfiguration',
            options={'verbose_name': 'Slack Configuration', 'verbose_name_plural': 'Slack Configurations'},
        ),
    ]
