# Generated by Django 4.2.23 on 2026-02-01 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboarding', '0002_onboardingprogress_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingChecklistLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(help_text='e.g. step_1_employee_hired', max_length=64, verbose_name='Step')),
                ('is_checked', models.BooleanField(default=True, help_text='True = checked, False = unchecked', verbose_name='Checked')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('reason', models.TextField(blank=True, help_text='Required when unchecking a step', null=True, verbose_name='Reason')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_logs', to='onboarding.onboardingprogress', verbose_name='Onboarding Progress')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Onboarding Checklist Log',
                'verbose_name_plural': 'Onboarding Checklist Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
