# Generated by Django 4.2.23 on 2026-02-01 06:30

from django.db import migrations, models

OLD_TO_NEW_STEP = {
    "step_1_employee_hired": "step_1",
    "step_2_offer_letter_issued": "step_2",
    "step_3_documents_collected": "step_3",
    "step_4_account_setup": "step_4",
    "step_5_welcome_completed": "step_5",
}


def update_checklist_log_steps(apps, schema_editor):
    OnboardingChecklistLog = apps.get_model("onboarding", "OnboardingChecklistLog")
    for old, new in OLD_TO_NEW_STEP.items():
        OnboardingChecklistLog.objects.filter(step=old).update(step=new)
    # Any other old step values (e.g. invalid) set to step_1 so constraint passes
    OnboardingChecklistLog.objects.exclude(
        step__in=list(OLD_TO_NEW_STEP.values())
    ).update(step="step_1")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_add_onboarding_checklist_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingprogress',
            name='step_1_employee_hired',
        ),
        migrations.RemoveField(
            model_name='onboardingprogress',
            name='step_2_offer_letter_issued',
        ),
        migrations.RemoveField(
            model_name='onboardingprogress',
            name='step_3_documents_collected',
        ),
        migrations.RemoveField(
            model_name='onboardingprogress',
            name='step_4_account_setup',
        ),
        migrations.RemoveField(
            model_name='onboardingprogress',
            name='step_5_welcome_completed',
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='step_1',
            field=models.BooleanField(default=False, verbose_name='Offer Letter Issued & Accepted'),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='step_10',
            field=models.BooleanField(default=False, verbose_name='Email ID Created'),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='step_11',
            field=models.BooleanField(default=False, verbose_name='System Login Credentials Shared'),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='step_12',
            field=models.BooleanField(default=False, verbose_name='Access to Tools & Platforms Granted (CRM, Project Tools, Drive, etc.)'),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='step_13',
            field=models.BooleanField(default=False, verbose_name='Asset Acknowledgment Form Signed'),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='step_14',
            field=models.BooleanField(default=False, verbose_name='Code of Conduct Signed'),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='step_15',
            field=models.BooleanField(default=False, verbose_name='Data Protection & Confidentiality Policy Signed'),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='step_16',
            field=models.BooleanField(default=False, verbose_name='POSH / Workplace Policy Acknowledged'),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='step_17',
            field=models.BooleanField(default=False, verbose_name='IT & Security Policy Acknowledged'),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='step_2',
            field=models.BooleanField(default=False, verbose_name='Joining Date Confirmed'),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='step_3',
            field=models.BooleanField(default=False, verbose_name='Personal Details Form Collected'),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='step_4',
            field=models.BooleanField(default=False, verbose_name='ID Proof & Address Proof Received'),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='step_5',
            field=models.BooleanField(default=False, verbose_name='Education Certificates Received'),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='step_6',
            field=models.BooleanField(default=False, verbose_name='Previous Employment Proof / Pay Slips Collected'),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='step_7',
            field=models.BooleanField(default=False, verbose_name='PF / ESIC / UAN Details Collected (if applicable)'),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='step_8',
            field=models.BooleanField(default=False, verbose_name='NDA & Employment Agreement Signed'),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='step_9',
            field=models.BooleanField(default=False, verbose_name='Laptop / Desktop Issued'),
        ),
        migrations.RunPython(update_checklist_log_steps, noop_reverse),
        migrations.AlterField(
            model_name='onboardingchecklistlog',
            name='step',
            field=models.CharField(choices=[('step_1', 'Offer Letter Issued & Accepted'), ('step_2', 'Joining Date Confirmed'), ('step_3', 'Personal Details Form Collected'), ('step_4', 'ID Proof & Address Proof Received'), ('step_5', 'Education Certificates Received'), ('step_6', 'Previous Employment Proof / Pay Slips Collected'), ('step_7', 'PF / ESIC / UAN Details Collected (if applicable)'), ('step_8', 'NDA & Employment Agreement Signed'), ('step_9', 'Laptop / Desktop Issued'), ('step_10', 'Email ID Created'), ('step_11', 'System Login Credentials Shared'), ('step_12', 'Access to Tools & Platforms Granted (CRM, Project Tools, Drive, etc.)'), ('step_13', 'Asset Acknowledgment Form Signed'), ('step_14', 'Code of Conduct Signed'), ('step_15', 'Data Protection & Confidentiality Policy Signed'), ('step_16', 'POSH / Workplace Policy Acknowledged'), ('step_17', 'IT & Security Policy Acknowledged')], db_index=True, max_length=64, verbose_name='Step'),
        ),
        migrations.AddIndex(
            model_name='onboardingchecklistlog',
            index=models.Index(fields=['progress', 'step'], name='onb_log_progress_step_idx'),
        ),
        migrations.AddConstraint(
            model_name='onboardingchecklistlog',
            constraint=models.CheckConstraint(check=models.Q(('step__in', ['step_1', 'step_2', 'step_3', 'step_4', 'step_5', 'step_6', 'step_7', 'step_8', 'step_9', 'step_10', 'step_11', 'step_12', 'step_13', 'step_14', 'step_15', 'step_16', 'step_17'])), name='onb_log_step_valid'),
        ),
    ]
