# Generated by Django 4.2.23 on 2026-02-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_clear_onboarding_checklist_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingprogress',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived onboarding entries are hidden from default view.', verbose_name='Archived'),
        ),
    ]
